name: iamb
base: core24
version: "v0.0.10"
summary: A Matrix client for Vim addicts
description: |
  This project is a work-in-progress, and there's still a lot to be implemented,
  but much of the basic client functionality is already present.

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:
  armhf:

parts:
  iamb:
    plugin: rust
    source: https://github.com/ulyssa/iamb/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz
    
apps:
  iamb:
    command: bin/iamb
    plugs:
      - network
