name: iamb
base: core22
adopt-info: iamb
summary: A Matrix client for Vim addicts
description: |
  This project is a work-in-progress, and there's still a lot to be implemented,
  but much of the basic client functionality is already present.

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: amd64
  - build-on: armhf
  
parts:
  iamb:
    plugin: rust
    source: https://github.com/ulyssa/iamb.git
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags)"
    
apps:
  iamb:
    command: bin/iamb
    plugs:
      - network
