name: iamb
base: core22
adopt-info: iamb
summary: A Matrix client for Vim addicts
description: |
  This project is a work-in-progress, and there's still a lot to be implemented,
  but much of the basic client functionality is already present.

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: amd64
  - build-on: armhf
  
parts:
  iamb:
    plugin: rust
    source: https://github.com/ulyssa/iamb.git
    override-pull: |
      craftctl default
      git fetch --tags
      last_committed_tag="$(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9]+)?$' | head -n 1)"
      last_released_tag="$(snap info iamb | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # stable, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
       git fetch
       git checkout "${last_committed_tag}"
      fi

      version="$(git describe --tags)"
      craftctl set version="$version"      


apps:
  iamb:
    command: bin/iamb
    plugs:
      - network
