name: iamb
base: core24
version: 'v0.0.11'
summary: A Matrix client for Vim addicts
description: |
  This project is a work-in-progress, and there's still a lot to be implemented,
  but much of the basic client functionality is already present.

grade: stable
confinement: strict

platforms:
  s390x:
    build-on: [s390x]
    build-for: [s390x]
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  riscv64:
    build-on: [riscv64]
    build-for: [riscv64]

parts:
  iamb:
    plugin: rust
    source: https://github.com/ulyssa/iamb
    source-type: git
    source-tag: v0.0.11

apps:
  iamb:
    command: bin/iamb
    plugs:
      - network
      - network-bind
